name: Deploy Pages
description: 'Download the artifact and deploy to GitHub Pages'

inputs:
  group:
    description: Group matching the artifacts
    required: false
    default: '*'

runs:
  using: 'composite'
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.group }}
        # path: public/${{ github.run_id }}
        path: public

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        clean: false
