name: Install Dependencies action
description: Caches and installs dependencies for a given path
inputs:
  dir-path:
    description: Path to the directory
    required: true
  keytar-host-mirror:
    description: Keytar binary host mirror
    required: false
  sqlite3-host-mirror:
    description: SQLite3 binary host mirror
    required: false
  skip-postinstall:
    description: Skip postinstall
    required: false
    default: '0'

runs:
  using: 'composite'
  steps:
    - name: Check if caching should be enabled
      id: should-cache
      shell: bash
      run: |
        # Enable caching for PR branches: fe/, be/, fe-be/, feature/, bugfix/
        # Skip caching for: ric/, latest, and other release branches
        if [[ "${{ github.ref_name }}" =~ ^(fe|be|fe-be|feature|bugfix)/ ]]; then
          echo "enabled=true" >> $GITHUB_OUTPUT
          echo "🚀 Caching enabled for branch: ${{ github.ref_name }}"
        else
          echo "enabled=false" >> $GITHUB_OUTPUT
          echo "⚡ Caching disabled for branch: ${{ github.ref_name }}"
        fi

    - name: Cache Yarn dependencies
      if: steps.should-cache.outputs.enabled == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/yarn
          ${{ inputs.dir-path }}/node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ inputs.dir-path }}-${{ hashFiles(format('{0}/yarn.lock', inputs.dir-path), format('{0}/package.json', inputs.dir-path)) }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ inputs.dir-path }}-
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      working-directory: ${{ inputs.dir-path }}
      shell: bash
      run: |
        # todo: uncomment after build our binaries
        # export npm_config_keytar_binary_host_mirror=${{ inputs.keytar-host-mirror }}
        # export npm_config_node_sqlite3_binary_host_mirror=${{ inputs.sqlite3-host-mirror }}

        yarn install --frozen-lockfile --network-timeout 1000000
