name: "API Install"

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
jobs:
  api_install:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'custom file'
        run: |
          mkdir -p release
          echo "Artifact 1 content" > release/art1.txt
          echo "Artifact 2 content" > release/art2.txt
          echo "Artifact 3 content" > release/diff_name_art3.txt

      - name: 'store artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'artifact'
          path: |
            release/art*
            package.json
      - name: 'store artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'diff'
          path: |
            release/diff*

      - name: 'Store builds'
        env:
          AWS_BUCKET_NAME_TEST: ${{ secrets.AWS_BUCKET_NAME_TEST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          rm release/._* ||:
          chmod +x .circleci/build/sum_sha256.sh
          .circleci/build/sum_sha256.sh
          applicationVersion=$(jq -r '.version' redisinsight/package.json)

          aws s3 cp release/ s3://${AWS_BUCKET_NAME_TEST}/private/builds/some_date/${{ github.sha }}_${applicationVersion} --recursive
#      - name: 'Setup Node'
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.15'
#          cache: 'yarn'
#
#      - name: 'Install API dependencies'
#        working-directory: './redisinsight/api'
#        run: 'yarn install --frozen-lockfile'
#
#      - name: 'Run code analysis'
#        working-directory: './redisinsight/api'
#        run: 'yarn test:cov'
#
#      - name: 'Build Electron Linux'
#        run: |
#          yarn --cwd redisinsight/api install --frozen-lockfile --ignore-optional
#          yarn --cwd redisinsight install --frozen-lockfile --ignore-optional
#          yarn install --frozen-lockfile
#          yarn build:statics
#          yarn package:prod
