name: AWS Development

on:
  workflow_call:
    inputs:
      pre-release:
        type: boolean
        default: false

env:
  AWS_BUCKET_NAME_TEST: ${{ vars.AWS_BUCKET_NAME_TEST }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  s3:
    name: Upload to s3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      uses: ./.github/actions/get-current-date

    - name: Download builds
      uses: actions/download-artifact@v4
      with:
        pattern: '*-builds'
        path: release
        merge-multiple: true

    - run: ls -R ./release

    - name: Set sub path for dev builds
      if: ${{ !inputs.pre-release }}
      run: |
        echo "SUB_PATH=dev-builds/${{ steps.date.outputs.date }}/${{ github.run_id }}" >> $GITHUB_ENV

    - name: Set sub path for pre-release builds and copy to upgrades folder
      if: inputs.pre-release
      run: |
        APP_VERSION=$(jq -r '.version' redisinsight/package.json)
        echo "SUB_PATH=pre-release/${APP_VERSION}" >> $GITHUB_ENV

        aws s3 rm s3://${AWS_BUCKET_NAME_TEST}/public/upgrades --recursive
        aws s3 cp release/ s3://${AWS_BUCKET_NAME_TEST}/public/upgrades --recursive

    - name: Upload builds to s3 bucket
      run: |
        aws s3 cp release/ s3://${AWS_BUCKET_NAME_TEST}/public/upgrades --recursive
        # aws s3 cp release/ s3://${AWS_BUCKET_NAME_TEST}/public/${SUB_PATH} --recursive

    - name: Generate job summary
      run: |
        node ./.github/generate-build-summary.js

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs: 's3'
    if: ${{ !inputs.pre-release }}
    runs-on: ubuntu-latest

    steps:
    - name: Merge artifacts by pattern
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: remove-artifacts
        pattern: '*'
        delete-merged: true

    - name: Delete merged artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.merge-artifacts.outputs.artifact-id }}
          });
