name: Build

on:
  # Called for Release workflows
  workflow_call:
    inputs:
      environment:
        description: Environment to run build
        type: string
        default: 'staging'

      target:
        description: Build target
        type: string
        default: 'all'

      debug:
        description: Enable SSH Debug
        type: boolean

jobs:
  build-macos:
    if: contains(inputs.target, 'macos') || inputs.target == 'all'
    uses: ./.github/workflows/pipeline-build-macos.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      target: ${{ inputs.target }}
      debug: ${{ inputs.debug }}
