name: ❗ Release (prod)

on:
  push:
    branches:
      - 'latest'

jobs:
  tests-prod:
    name: Run all tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      group_tests: 'without_e2e'
      short_rte_list: false

  builds-prod:
    name: Create all builds for release
    uses: ./.github/workflows/build.yml
    needs: tests-prod
    secrets: inherit
    with:
      environment: 'production'
      target: 'all'

  e2e-docker-tests:
    name: E2E Docker tests
    needs: builds-prod
    uses: ./.github/workflows/tests-e2e-docker.yml
    secrets: inherit

  e2e-appimage-tests:
    name: E2E AppImage tests
    needs: builds-prod
    uses: ./.github/workflows/tests-e2e-appimage.yml
    secrets: inherit

  virustotal-prod:
    name: Virustotal
    uses: ./.github/workflows/virustotal.yml
    needs: builds-prod
    secrets: inherit
    with:
      skip_report: true

  aws-upload-prod:
    name: Realse to AWS S3
    uses: ./.github/workflows/aws-upload-prod.yml
    needs: virustotal-prod
    secrets: inherit

  docker-prod:
    name: Release docker images
    uses: ./.github/workflows/release-docker.yml
    needs: aws-upload-prod
    secrets: inherit

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs: [aws-upload-prod, e2e-docker-tests, e2e-appimage-tests]
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Merge artifacts by pattern
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: remove-artifacts
        pattern: '*'
        delete-merged: true

    - name: Delete merged artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.merge-artifacts.outputs.artifact-id }}
          });
