name: ❗ Release (prod)

on:
  push:
    branches:
      - 'latest'
      - 'latest_mas_new'

jobs:
  builds-prod:
    name: Create all builds for release
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: 'production'
      target: 'all'

  virustotal-prod:
    name: Virustotal
    uses: ./.github/workflows/virustotal.yml
    needs: builds-prod
    secrets: inherit
    with:
      skip_report: true

  aws-upload-prod:
    name: Realse to AWS S3
    uses: ./.github/workflows/aws-upload-prod.yml
    needs: virustotal-prod
    secrets: inherit

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs: [aws-upload-prod]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove all artifacts
        uses: ./.github/actions/remove-artifacts
