name: 📖 Release (stage)

on:
  push:
    branches:
      - 'release/**'

jobs:
  tests:
    name: Release stage tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      group_tests: 'without_e2e'
      short_rte_list: false

  builds:
    name: Release stage builds
    uses: ./.github/workflows/build.yml
    needs: tests
    secrets: inherit
    with:
      environment: 'staging'
      target: 'all'

  aws:
    uses: ./.github/workflows/aws-upload-dev.yml
    needs: [builds]
    secrets: inherit
    if: always()
    with:
      pre-release: true

  e2e-docker-tests:
    needs: builds
    uses: ./.github/workflows/tests-e2e-docker.yml
    secrets: inherit

  e2e-appimage-tests:
    needs: builds
    uses: ./.github/workflows/tests-e2e-appimage.yml
    secrets: inherit

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs: [aws, e2e-docker-tests, e2e-appimage-tests]
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Merge artifacts by pattern
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: remove-artifacts
        pattern: '*'
        delete-merged: true

    - name: Delete merged artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.merge-artifacts.outputs.artifact-id }}
          });
