name: Simple Tests

on:
  push:
    branches:
      - 'feature/cache-node-modules'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            redisinsight/yarn.lock
            redisinsight/api/yarn.lock

      - name: Install dependencies
        run: |
          echo "📦 Installing root dependencies..."
          yarn install --frozen-lockfile
          
          echo "📦 Installing redisinsight dependencies..."
          yarn --cwd redisinsight install --frozen-lockfile
          
          echo "📦 Installing API dependencies..."
          yarn --cwd redisinsight/api install --frozen-lockfile

      - name: Run linting
        run: yarn lint
