name: Tests BE
on:
  workflow_call:
    inputs:
      skip-electron-deps:
        description: Skip install electron dependencies
        type: boolean
        default: false
        required: false

env:
  SLACK_AUDIT_REPORT_CHANNEL: ${{ secrets.SLACK_AUDIT_REPORT_CHANNEL }}
  SLACK_AUDIT_REPORT_KEY: ${{ secrets.SLACK_AUDIT_REPORT_KEY }}
  REPORT_NAME: 'report-be'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        working-directory: 'redisinsight/api'
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000

      - name: Unit tests API
        timeout-minutes: 20
        run: yarn --cwd redisinsight/api/ test:cov --ci --silent

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.REPORT_NAME }}
          path: redisinsight/api/report

      - name: Get current date
        id: date
        if: always()
        uses: ./.github/actions/get-current-date

      - name: Deploy report
        uses: ./.github/actions/deploy-test-reports
        if: always()
        with:
          group: 'report'
          path: '${{ vars.DEFAULT_TEST_REPORTS_URL }}/${{ steps.date.outputs.date }}/${{ github.run_id }}/${{ env.REPORT_NAME }}'
          AWS_BUCKET_NAME_TEST: ${{ vars.AWS_BUCKET_NAME_TEST }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
