name: ✅ Tests

on:
  push:
    branches:
      - 'fe/**'
      - 'be/**'
      - 'e2e/**'

  workflow_dispatch:
    inputs:
      group_tests:
        description: Run group of tests
        default: 'all'
        type: choice
        options:
          - all
          - without_e2e
      redis_client:
        description: Library to use for redis connection
        default: 'ioredis'
        type: choice
        options:
          - ioredis
          - node-redis
      debug:
        description: Enable SSH Debug (IT and E2E)
        default: false
        type: boolean

  workflow_call:
    inputs:
      group_tests:
        description: Run group of tests
        type: string
        default: 'all'
      short_rte_list:
        description: Use short rte list
        type: boolean
        default: true
      debug:
        description: Enable SSH Debug
        default: false
        type: boolean

# Cancel a previous run workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    uses: ./.github/workflows/pipeline-build-docker.yml
    secrets: inherit

  integration-tests-nightly:
    needs: build-docker
    uses: ./.github/workflows/tests-integration.yml
    secrets: inherit
    with:
      build: 'docker'
      report: true
      short_rte_list: false
